package io.lifeengine.runtime.observability;

import io.lifeengine.runtime.app.RuntimeApplication;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;

/**
 * End-to-end contract for the build identity on {@code /actuator/info} (KAN-195 / T3, mirroring Auth
 * KAN-194 / LIFE-OPS-02 §2.2). Boots the full app with security ENABLED, so it also proves that
 * {@code /actuator/info} is internal-readable without a token while other routes still require auth. The git
 * block is populated from the real {@code git.properties} generated by git-commit-id during this build.
 *
 * <p>Named {@code *Test} (not {@code *IT}) so it runs in the surefire lane that CI executes — Runtime has no
 * failsafe split.
 */
@SpringBootTest(classes = RuntimeApplication.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureWebTestClient
@ActiveProfiles("test")
@TestPropertySource(
        properties = {
            "lifeengine.runtime.security.enabled=true",
            "lifeengine.security.jwt.secret=" + RuntimeActuatorInfoIdentityTest.SECRET,
            // Proves deployment.environment is configuration-driven, not hardcoded.
            "lifeengine.deployment.env=citest",
            "management.endpoints.web.exposure.include=health,info,prometheus"
        })
class RuntimeActuatorInfoIdentityTest {

    static final String SECRET = "test-jwt-secret-at-least-32-bytes-long-xxxx";

    @Autowired
    private WebTestClient webTestClient;

    @Test
    @DisplayName("GET /actuator/info (no auth) → 200 with §2.2 identity: real commit, env from config")
    void actuatorInfoExposesBuildIdentity() {
        webTestClient
                .get()
                .uri("/actuator/info")
                .exchange()
                .expectStatus()
                .isOk()
                .expectBody()
                .jsonPath("$.service.name")
                .isEqualTo("life-engine-runtime")
                .jsonPath("$.service.version")
                .isNotEmpty()
                // From lifeengine.deployment.env — configuration-driven.
                .jsonPath("$.deployment.environment")
                .isEqualTo("citest")
                // Real commit from git.properties generated by git-commit-id in this build.
                .jsonPath("$.git.commit.id")
                .isNotEmpty()
                .jsonPath("$.build.timestamp")
                .isNotEmpty();
    }

    @Test
    @DisplayName("/actuator/info is internal-readable, but a protected route still denies (no over-exposure)")
    void actuatorInfoDoesNotLoosenSecurity() {
        webTestClient.get().uri("/actuator/info").exchange().expectStatus().isOk();
        webTestClient.get().uri("/api/runtime/workflows").exchange().expectStatus().isUnauthorized();
    }
}
